<?php
return [
    'title' => 'Portfolio de Nicolas Deprets',
    'header' => 'Développeur Web | Objectif : devenir Dev Full Stack',
    'repositories' => 'Dépôts',
    'skills' => 'Compétences',
    'experience' => "Années d'expérience",
    'about' => 'À propos de moi',
    'about_text' => "Je m'appelle Nicolas Deprets, j'ai 20 ans et je suis un apprenti développeur passionné par les nouvelles technologies. J'aime explorer comment les technologies numériques peuvent transformer notre monde et améliorer nos vies.",
    'projects' => 'Projets',
    'competences' => 'Compétences',
    'tab_langages' => 'Langages de code',
    'tab_hebergeur' => 'Hébergeur',
    'tab_autre' => 'Autre',
    'school_path' => 'Parcours scolaire',
    'school_2024' => 'Assistant développeur web IFAPME de Charleroi. (E6K-A6K)',
    'school_2023' => 'Soins animalier à la Madelaine à Tournai',
    'school_2022' => 'Aide à la personne à Saint Charles à Péruwelz',
    'software_integration' => 'Logiciels / Intégration',
    'software_github_title' => 'GitHub',
    'software_github_desc' => 'Plateforme de gestion de versions et de collaboration.',
    'software_tailwind_title' => 'Tailwind CSS',
    'software_tailwind_desc' => 'Framework CSS utilitaire.',
    'software_fa_title' => 'FontAwesome',
    'software_fa_desc' => 'Kit d’icônes pour projets web.',
    'software_bootstrap_title' => 'Bootstrap',
    'software_bootstrap_desc' => 'Framework CSS pour design réactif.',
    'status_alternance' => "Statut : En attente d'une réponse d'alternance",
];
