<?php
return [
    'title' => 'Portfolio van Nicolas Deprets',
    'header' => 'Webontwikkelaar | Doel: Full Stack Ontwikkelaar worden',
    'repositories' => 'Repositories',
    'skills' => 'Vaardigheden',
    'experience' => 'Jaren Ervaring',
    'about' => 'Over Mij',
    'about_text' => "Mijn naam is Nicolas Deprets, ik ben 20 jaar oud en ik ben een leerling-ontwikkelaar die gepassioneerd is door nieuwe technologieën. Ik hou ervan om te ontdekken hoe digitale technologieën onze wereld kunnen transformeren en ons leven kunnen verbeteren.",
    'projects' => 'Projecten',
    'competences' => 'Vaardigheden',
    'tab_langages' => 'Programmeertalen',
    'tab_hebergeur' => 'Hosting',
    'tab_autre' => 'Overige',
    'school_path' => 'Schoolloopbaan',
    'school_2024' => 'Assistent webontwikkelaar IFAPME Charleroi. (E6K-A6K) (2024-2025)',
    'school_2023' => 'Dierenverzorging aan La Madelaine in Doornik (2023-2024)',
    'school_2022' => 'Hulp aan personen aan Saint Charles in Péruwelz',
    'software_integration' => 'Software / Integratie',
    'software_github_title' => 'GitHub',
    'software_github_desc' => 'Versiebeheer en samenwerkingsplatform.',
    'software_tailwind_title' => 'Tailwind CSS',
    'software_tailwind_desc' => 'Utility-first CSS framework.',
    'software_fa_title' => 'FontAwesome',
    'software_fa_desc' => 'Icoon toolkit voor webprojecten.',
    'software_bootstrap_title' => 'Bootstrap',
    'software_bootstrap_desc' => 'CSS-framework voor responsief ontwerp.',
    'status_alternance' => "Status: In afwachting van een antwoord op de stageaanvraag",
];
