<?php
return [
    'title' => "Nicolas Deprets' Portfolio",
    'header' => 'Web Developer | Goal: Become a Full Stack Developer',
    'repositories' => 'Repositories',
    'skills' => 'Skills',
    'experience' => 'Years of Experience',
    'about' => 'About Me',
    'about_text' => "My name is Nicolas Deprets, I'm 20 years old, and I am an apprentice developer passionate about new technologies. I love exploring how digital technologies can transform our world and improve our lives.",
    'projects' => 'Projects',
    'competences' => 'Skills',
    'tab_langages' => 'Programming Languages',
    'tab_hebergeur' => 'Hosting',
    'tab_autre' => 'Other',
    'school_path' => 'Education',
    'school_2024' => 'Web Developer Assistant at IFAPME Charleroi. (E6K-A6K) (2024-2025)',
    'school_2023' => 'Animal care at La Madelaine in Tournai (2023-2024)',
    'school_2022' => 'Personal care at Saint Charles in Péruwelz',
    'software_integration' => 'Software / Integration',
    'software_github_title' => 'GitHub',
    'software_github_desc' => 'Version control and collaboration platform.',
    'software_tailwind_title' => 'Tailwind CSS',
    'software_tailwind_desc' => 'Utility-first CSS framework.',
    'software_fa_title' => 'FontAwesome',
    'software_fa_desc' => 'Icon toolkit for web projects.',
    'software_bootstrap_title' => 'Bootstrap',
    'software_bootstrap_desc' => 'CSS framework for responsive design.',
    'status_alternance' => "Status: Waiting for an apprenticeship response",
];
